service: lambdaServerless-Cron
frameworkVersion: '3'
provider:
  name: aws
  runtime: python3.9
  region: ${opt:region, 'ap-south-1'}
  environment:
    STAGE: ${opt:stage, 'dev'}
functions:
  cronHandler:
    handler: handler.run
    memorySize: 3008
    timeout: 10
    tracing: Active
    
    events:
      - schedule: cron(0/2 * ? * MON-SAT *)



          

            